-- ============================================================================
-- ALPED PUNYA V3 — PRODUCTION V1 CORE SCHEMA
-- ============================================================================

-- 1. SOURCES TABLE (Source Authority Registry)
CREATE TABLE IF NOT EXISTS sources (
    source_id VARCHAR(64) PRIMARY KEY,          -- Strict 64-char SHA-256 Hex
    broker TEXT NOT NULL,
    environment TEXT NOT NULL,                  -- 'DEMO' | 'REAL'
    account_hash VARCHAR(64) NOT NULL,          -- SHA-256 of raw account number
    ea_identifier TEXT NOT NULL,                -- e.g. 'ALPED_BRIDGE_01'
    ea_version TEXT NOT NULL,                   -- e.g. '3.0.0'
    payload_version TEXT NOT NULL,              -- e.g. '1.0.0'
    schema_version TEXT NOT NULL DEFAULT '1.0.0',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_heartbeat_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. SYMBOLS TABLE
CREATE TABLE IF NOT EXISTS symbols (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_id VARCHAR(64) NOT NULL REFERENCES sources(source_id) ON DELETE CASCADE,
    symbol TEXT NOT NULL,
    digits INT NOT NULL,
    point NUMERIC(16, 8) NOT NULL,
    contract_size NUMERIC(16, 2) NOT NULL,
    volume_min NUMERIC(10, 2) NOT NULL,
    volume_max NUMERIC(10, 2) NOT NULL,
    volume_step NUMERIC(10, 2) NOT NULL,
    stop_level INT NOT NULL,
    trade_mode INT NOT NULL,
    currency_base TEXT NOT NULL,
    currency_profit TEXT NOT NULL,
    schema_version TEXT NOT NULL DEFAULT '1.0.0',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_symbols_source_symbol UNIQUE (source_id, symbol)
);
CREATE INDEX IF NOT EXISTS idx_symbols_source_symbol ON symbols (source_id, symbol);

-- 3. MARKET CANDLES TABLE (Canonical Time-Series Tier)
CREATE TABLE IF NOT EXISTS market_candles (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    source_id VARCHAR(64) NOT NULL REFERENCES sources(source_id) ON DELETE CASCADE,
    symbol TEXT NOT NULL,
    timeframe TEXT NOT NULL,                  -- 'M1', 'M5', 'M15', 'M30', 'H1', 'H4', 'D1'
    candle_time_utc TIMESTAMPTZ NOT NULL,     -- Canonical UTC generated by backend
    candle_time_epoch BIGINT NOT NULL,        -- Authoritative MT5 input epoch
    open NUMERIC(16, 6) NOT NULL,
    high NUMERIC(16, 6) NOT NULL,
    low NUMERIC(16, 6) NOT NULL,
    close NUMERIC(16, 6) NOT NULL,
    tick_volume BIGINT NOT NULL,
    spread INT NOT NULL,
    broker_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, -- Audit reference
    broker_gmt_offset INT NOT NULL,           -- Offset in seconds at bar time
    session TEXT NOT NULL,                    -- 'ASIA', 'LONDON', 'NEW_YORK', 'OVERLAP', etc.
    is_gap_recovered BOOLEAN DEFAULT FALSE,
    payload_version TEXT NOT NULL DEFAULT '1.0.0',
    schema_version TEXT NOT NULL DEFAULT '1.0.0',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_candles_source_sym_tf_time UNIQUE (source_id, symbol, timeframe, candle_time_utc)
);
CREATE INDEX IF NOT EXISTS idx_candles_query ON market_candles (source_id, symbol, timeframe, candle_time_utc DESC);
CREATE INDEX IF NOT EXISTS idx_candles_session ON market_candles (session, candle_time_utc);

-- 4. CANDLE GAPS TABLE (Schedule-Aware Audit Log)
CREATE TABLE IF NOT EXISTS candle_gaps (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    source_id VARCHAR(64) NOT NULL REFERENCES sources(source_id) ON DELETE CASCADE,
    symbol TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    gap_start_utc TIMESTAMPTZ NOT NULL,
    gap_end_utc TIMESTAMPTZ NOT NULL,
    expected_interval_seconds INT NOT NULL,
    missing_bars_count INT NOT NULL,
    status TEXT NOT NULL,                     -- 'DETECTED', 'RECOVERED', 'WEEKEND', 'MARKET_CLOSED', 'HOLIDAY', 'BROKER_MAINTENANCE', 'PERMANENT_UNAVAILABLE'
    classification_reason TEXT NOT NULL,
    detected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    recovered_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_candle_gaps_lookup ON candle_gaps (source_id, symbol, timeframe, status);

-- 5. MARKET TICKS TABLE (Configurable: Default TICK_OFF)
CREATE TABLE IF NOT EXISTS market_ticks (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    source_id VARCHAR(64) NOT NULL REFERENCES sources(source_id) ON DELETE CASCADE,
    symbol TEXT NOT NULL,
    tick_time_utc TIMESTAMPTZ NOT NULL,
    tick_time_epoch BIGINT NOT NULL,
    bid NUMERIC(16, 6) NOT NULL,
    ask NUMERIC(16, 6) NOT NULL,
    last NUMERIC(16, 6) DEFAULT 0,
    volume BIGINT DEFAULT 0,
    broker_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_ticks_query ON market_ticks (source_id, symbol, tick_time_utc DESC);

-- 6. ACCOUNT SNAPSHOTS TABLE
CREATE TABLE IF NOT EXISTS account_snapshots (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    source_id VARCHAR(64) NOT NULL REFERENCES sources(source_id) ON DELETE CASCADE,
    balance NUMERIC(16, 2) NOT NULL,
    equity NUMERIC(16, 2) NOT NULL,
    margin NUMERIC(16, 2) NOT NULL,
    free_margin NUMERIC(16, 2) NOT NULL,
    margin_level NUMERIC(10, 2),
    open_positions_count INT NOT NULL DEFAULT 0,
    snapshot_time_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    schema_version TEXT NOT NULL DEFAULT '1.0.0'
);
CREATE INDEX IF NOT EXISTS idx_account_snapshots ON account_snapshots (source_id, snapshot_time_utc DESC);

-- 7. POSITIONS TABLE (Current Open State - Account-Scoped Ticket Uniqueness)
CREATE TABLE IF NOT EXISTS positions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_id VARCHAR(64) NOT NULL REFERENCES sources(source_id) ON DELETE CASCADE,
    ticket BIGINT NOT NULL,
    symbol TEXT NOT NULL,
    type TEXT NOT NULL,                       -- 'BUY' | 'SELL'
    lots NUMERIC(10, 2) NOT NULL,
    open_price NUMERIC(16, 6) NOT NULL,
    open_time_utc TIMESTAMPTZ NOT NULL,
    sl NUMERIC(16, 6) DEFAULT 0,
    tp NUMERIC(16, 6) DEFAULT 0,
    current_price NUMERIC(16, 6) NOT NULL,
    profit NUMERIC(16, 2) NOT NULL,
    magic_number BIGINT DEFAULT 0,
    comment TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_positions_source_ticket UNIQUE (source_id, ticket)
);

-- 8. POSITION EVENTS TABLE (Immutable Audit Trail for Trading Journal)
CREATE TABLE IF NOT EXISTS position_events (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    source_id VARCHAR(64) NOT NULL REFERENCES sources(source_id) ON DELETE CASCADE,
    ticket BIGINT NOT NULL,
    event_type TEXT NOT NULL,                 -- 'OPEN', 'MODIFY_SL', 'MODIFY_TP', 'PARTIAL_CLOSE', 'CLOSE'
    symbol TEXT NOT NULL,
    lots NUMERIC(10, 2) NOT NULL,
    price NUMERIC(16, 6) NOT NULL,
    sl NUMERIC(16, 6),
    tp NUMERIC(16, 6),
    profit NUMERIC(16, 2) DEFAULT 0,
    event_time_utc TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_pos_events_query ON position_events (source_id, ticket, event_time_utc ASC);
